environment = "production"
srv_name = "yoursrvname"
disk_size = "100"
tags = "yoursrvname"
ssh_pub_key = "ssh-rsa your public key"
ssh_user = "youruser"
storage_bucket = "yoursrvname"
type = "e2-standard-2"